on: [push]

jobs:
  build_releases:
    name: Release builder
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python: ['3.8.8']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build release(s)
        #uses: MissionBio/actions@main
        uses: aljosa/missionbio-actions@windows-build-support
        with:
          source_path: .
          build_path: build
          electron_path: mosaic-streamlit

      - uses: actions/upload-artifact@v2
        with:
          name: mosaic-streamlit-${{ env.PRODUCT_OS_AND_VERSION }}.zip
          path: ${{ github.workspace }}/release.zip
          if-no-files-found: ignore
        if: ${{ env.SYSTEM_NAME != 'macos' }}

      - uses: actions/upload-artifact@v2
        with:
          name: mosaic-streamlit-${{ env.PRODUCT_OS_AND_VERSION }}.dmg
          path: ${{ github.workspace }}/release.dmg
          if-no-files-found: ignore
        if: ${{ env.SYSTEM_NAME == 'macos' }}

