on: [push]

jobs:
  build_releases:
    name: Release builder
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'
          architecture: 'x64'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build release(s)
        uses: aljosa/actions@main
        with:
          source_path: .
          build_path: build
          build_script: ./build.sh
          electron_path: mosaic-streamlit

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SYSTEM_NAME }}-runtime.zip
          path: ${{ github.workspace }}/runtime.zip
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SYSTEM_NAME }}-release.zip
          path: ${{ github.workspace }}/release.zip
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SYSTEM_NAME }}-release.dmg
          path: ${{ github.workspace }}/release.dmg
          if-no-files-found: ignore

